### ISSUE TITLE
support of other mainnet address types

### ISSUE THREAD

**Issue by ErfanMN** [richardkiss/pycoin_rs#1]
Hi, Richard. I was wondering does this package support other mainnet addresses ? like `P2SH `or `segwit` ? 

I just see your test file is written using `.p2pkh_address(MAINNET)`

**Comment by richardkiss** [comment]
Resolved in c4e02b8c100aaab1a08fd8f07dc76538986c03be and with this [PR](https://github.com/richardkiss/pycoin_rs/pull/2)
